### PR TITLE
Make build CI copy commit name

### PR DESCRIPTION
**Pull request by Dionysusnu**

### CODE REVIEW

**Comment by osyrisrblx** [comment]
I don't think I see the point here.

Generated files might change from data from Roblox API dump, devhub scrapper repository, or from manual code changes in this repository. I think putting the latest commit author/message there might mask that?

**Comment by Dionysusnu** [comment]
Well yes, but at the same time, it's unfortunate to lose the actual change. For example, if I were to commit "Update error type to include object parameter", then the CI would just say "update generated files". Losing the commit message, making it harder to see things from an overview.

**Comment by Dionysusnu** [comment]
Maybe we should make it adaptive, depending on the trigger? State "Daily API dump update" if it was triggered by cron, state the commit message if triggered by a commit push?

**Comment by osyrisrblx** [comment]
To clarify, we might have a manual commit that triggers a build, but automated information could also update simultaneously if something has changed between scheduled automatic builds. This happens pretty frequently.

**Comment by Dionysusnu** [comment]
So, my point is that it's currently unknown what caused the CI build. With this PR, it will specify what initiated the action. You're right that automatic builds stating the last commit would be confusing, so I'm open to changing that. For example making it state "Daily generated files update" in that case.

**Pull request closed without merging**
