### PR TITLE
Add DS V2 Types

### PR DESCRIPTION
**Pull request by OverHash**

### CODE REVIEW

**Comment by LuckyTortoise** [comment]
I'm willing to help, what else needs to be added?

**Comment by OverHash** [comment]
> I'm willing to help, what else needs to be added?

Currently more testing on actually using this in real games with typings. I've already checked with a few of my projects, and they compiled fine after some minimal necessary changes.

If you have any projects that use roblox-ts previously, downloading these typings locally and installing them & then seeing if there is any issues with compilation will greatly help!

I'm going to do some more extensive testing myself locally to make sure that everything works as expected, however.

**Comment by OverHash** [comment]
On that note, I think these typings are ready for review and just need some people to try them out.

**Comment by Kampfkarren** [comment]
I need this soon.

**Pull request merged**
